name: filepicker_windows
description: A plugin that uses FFI to offer file selection in Windows using the modern common item dialog box.
version: 1.0.0
homepage: https://github.com/timsneath/filepicker_windows

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  win32: ^1.7.3
  ffi: ^0.1.3

dev_dependencies:
  lint: ^1.2.0