name: filepicker_windows
description: A plugin that uses FFI to offer file selection in Windows using the modern common item dialog box.
version: 1.0.0
homepage: https://github.com/timsneath/filepicker_windows

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  ffi: ^0.2.0-nullsafety.1
  win32: ^2.0.0-nullsafety.0

dev_dependencies:
  lint: ^1.5.1